// SB Coffee Week 2026 — Cafe & Restaurant Data
// Event: March 19–28, 2026
// Source: Santa Barbara Independent
const SOURCE_URL =
  "https://www.independent.com/2026/03/18/here-comes-santa-barbara-coffee-week/";

const AREA_COLORS = {
  Downtown: "#e63946",
  "Upper State": "#e9c46a",
  Westside: "#457b9d",
  Goleta: "#2a9d8f",
  Carpinteria: "#8338ec",
  Montecito: "#f4a261",
};

const restaurants = [
  // ==========================================
  // JUST COFFEE (justCoffee: true)
  // ==========================================

  // --- Goleta ---
  {
    name: "Del Pueblo Café",
    address: "5134 Hollister Ave, Goleta, CA",
    website: null,
    phone: null,
    instagram: null,
    area: "Goleta",
    lat: 34.4353,
    lng: -119.8042,
    mapUrl: null,
    appleMapsUrl: null,
    justCoffee: true,
    coffeeWithFood: false,
    coffeeAsCocktail: false,
    menuItems: [],
  },

  // --- Dune Coffee (4 locations) ---
  {
    name: "Dune Coffee (Anacapa)",
    address: "528 Anacapa St, Santa Barbara, CA",
    website: "https://www.dunecoffee.com",
    phone: null,
    instagram: "dunecoffeeroasters",
    area: "Downtown",
    lat: 34.4178,
    lng: -119.6941,
    mapUrl: null,
    appleMapsUrl: null,
    justCoffee: true,
    coffeeWithFood: false,
    coffeeAsCocktail: false,
    menuItems: [],
  },
  {
    name: "Dune Coffee (Calle Real)",
    address: "5915 Calle Real, Goleta, CA",
    website: "https://www.dunecoffee.com",
    phone: null,
    instagram: "dunecoffeeroasters",
    area: "Goleta",
    lat: 34.4413,
    lng: -119.8306,
    mapUrl: null,
    appleMapsUrl: null,
    justCoffee: true,
    coffeeWithFood: false,
    coffeeAsCocktail: false,
    menuItems: [],
  },
  {
    name: "Dune Coffee (State St)",
    address: "1101 State St, Santa Barbara, CA",
    website: "https://www.dunecoffee.com",
    phone: null,
    instagram: "dunecoffeeroasters",
    area: "Downtown",
    lat: 34.4233,
    lng: -119.7043,
    mapUrl: null,
    appleMapsUrl: null,
    justCoffee: true,
    coffeeWithFood: false,
    coffeeAsCocktail: false,
    menuItems: [],
  },
  {
    name: "Dune Coffee (Storke)",
    address: "250 Storke Rd, Goleta, CA",
    website: "https://www.dunecoffee.com",
    phone: null,
    instagram: "dunecoffeeroasters",
    area: "Goleta",
    lat: 34.4330,
    lng: -119.8622,
    mapUrl: null,
    appleMapsUrl: null,
    justCoffee: true,
    coffeeWithFood: false,
    coffeeAsCocktail: false,
    menuItems: [],
  },

  // --- Lighthouse Coffee (5 locations) ---
  {
    name: "Lighthouse Coffee (Cliff Dr)",
    address: "1819 Cliff Dr Ste C, Santa Barbara, CA",
    website: "https://www.lighthousecoffee.com",
    phone: null,
    instagram: "lighthousecoffee",
    area: "Westside",
    lat: 34.4013,
    lng: -119.7224,
    mapUrl: null,
    appleMapsUrl: null,
    justCoffee: true,
    coffeeWithFood: false,
    coffeeAsCocktail: false,
    menuItems: [],
  },
  {
    name: "Lighthouse Coffee (Chapala)",
    address: "711 Chapala St, Santa Barbara, CA",
    website: "https://www.lighthousecoffee.com",
    phone: null,
    instagram: "lighthousecoffee",
    area: "Downtown",
    lat: 34.4179,
    lng: -119.6991,
    mapUrl: null,
    appleMapsUrl: null,
    justCoffee: true,
    coffeeWithFood: false,
    coffeeAsCocktail: false,
    menuItems: [],
  },
  {
    name: "Lighthouse Coffee (Haley)",
    address: "401 E Haley St, Santa Barbara, CA",
    website: "https://www.lighthousecoffee.com",
    phone: null,
    instagram: "lighthousecoffee",
    area: "Downtown",
    lat: 34.4199,
    lng: -119.6914,
    mapUrl: null,
    appleMapsUrl: null,
    justCoffee: true,
    coffeeWithFood: false,
    coffeeAsCocktail: false,
    menuItems: [],
  },
  {
    name: "Lighthouse Coffee (Turnpike)",
    address: "199 S Turnpike Rd, Goleta, CA",
    website: "https://www.lighthousecoffee.com",
    phone: null,
    instagram: "lighthousecoffee",
    area: "Goleta",
    lat: 34.4375,
    lng: -119.7900,
    mapUrl: null,
    appleMapsUrl: null,
    justCoffee: true,
    coffeeWithFood: false,
    coffeeAsCocktail: false,
    menuItems: [],
  },
  {
    name: "Lighthouse Coffee (Calle Real)",
    address: "5696 Calle Real, Goleta, CA",
    website: "https://www.lighthousecoffee.com",
    phone: null,
    instagram: "lighthousecoffee",
    area: "Goleta",
    lat: 34.4408,
    lng: -119.8230,
    mapUrl: null,
    appleMapsUrl: null,
    justCoffee: true,
    coffeeWithFood: false,
    coffeeAsCocktail: false,
    menuItems: [],
  },

  // --- Carpinteria ---
  {
    name: "Lucky Llama Coffee House",
    address: "5100 Carpinteria Ave, Carpinteria, CA",
    website: null,
    phone: null,
    instagram: "luckyllamacoffee",
    area: "Carpinteria",
    lat: 34.3983,
    lng: -119.5172,
    mapUrl: null,
    appleMapsUrl: null,
    justCoffee: true,
    coffeeWithFood: false,
    coffeeAsCocktail: false,
    menuItems: [],
  },

  // --- Downtown ---
  {
    name: "Santa Barbara Roasting Company",
    address: "321 Motor Way, Santa Barbara, CA",
    website: "https://www.sbcoffee.com",
    phone: "805-962-0320",
    instagram: "sbroastingco",
    area: "Downtown",
    lat: 34.4156,
    lng: -119.6870,
    mapUrl: null,
    appleMapsUrl: null,
    justCoffee: true,
    coffeeWithFood: false,
    coffeeAsCocktail: false,
    menuItems: [],
  },

  // ==========================================
  // COFFEE WITH FOOD (coffeeWithFood: true)
  // ==========================================

  // --- Carpinteria ---
  {
    name: "Carp Moon Café",
    address: "4991 Carpinteria Ave, Carpinteria, CA",
    website: null,
    phone: null,
    instagram: null,
    area: "Carpinteria",
    lat: 34.3985,
    lng: -119.5188,
    mapUrl: null,
    appleMapsUrl: null,
    justCoffee: false,
    coffeeWithFood: true,
    coffeeAsCocktail: false,
    menuItems: [],
  },

  // --- Downtown (reused from burger week) ---
  {
    name: "Crushcakes & Café (Anacapa)",
    address: "1315 Anacapa St, Santa Barbara, CA",
    website: "https://www.crushcakes.com",
    phone: "805-963-9353",
    instagram: "crushcakescafe",
    area: "Downtown",
    lat: 34.425637,
    lng: -119.705214,
    mapUrl: "https://maps.app.goo.gl/BwkDspDsomjtTNk79",
    appleMapsUrl: "https://maps.apple/p/u2LdIBaUBhX.u.z",
    justCoffee: false,
    coffeeWithFood: true,
    coffeeAsCocktail: false,
    menuItems: [],
  },

  // --- Goleta (reused from burger week) ---
  {
    name: "Crushcakes & Café (Hollister)",
    address: "5392 Hollister Ave, Goleta, CA",
    website: "https://www.crushcakes.com",
    phone: "805-845-2780",
    instagram: "crushcakescafe",
    area: "Goleta",
    lat: 34.435346,
    lng: -119.812297,
    mapUrl: "https://maps.app.goo.gl/YXrd5iwBn4oCouXA9",
    appleMapsUrl: "https://maps.apple/p/Ir9WS14tYcDv6N",
    justCoffee: false,
    coffeeWithFood: true,
    coffeeAsCocktail: false,
    menuItems: [],
  },

  // --- Downtown ---
  {
    name: "Goodland Waffles & Melts",
    address: "1131 State St, Santa Barbara, CA",
    website: null,
    phone: null,
    instagram: "goodlandwaffles",
    area: "Downtown",
    lat: 34.4238,
    lng: -119.7049,
    mapUrl: null,
    appleMapsUrl: null,
    justCoffee: false,
    coffeeWithFood: true,
    coffeeAsCocktail: false,
    menuItems: [],
  },

  // --- Renaud's Patisserie (4 locations) ---
  {
    name: "Renaud's Patisserie (3315 State)",
    address: "3315 State St, Santa Barbara, CA",
    website: "https://www.renaudspatisserie.com",
    phone: "805-569-2400",
    instagram: "renaudspatisserie",
    area: "Upper State",
    lat: 34.4393,
    lng: -119.7358,
    mapUrl: null,
    appleMapsUrl: null,
    justCoffee: false,
    coffeeWithFood: true,
    coffeeAsCocktail: false,
    menuItems: [],
  },
  {
    name: "Renaud's Patisserie (1324 State)",
    address: "1324 State St, Santa Barbara, CA",
    website: "https://www.renaudspatisserie.com",
    phone: "805-892-2800",
    instagram: "renaudspatisserie",
    area: "Upper State",
    lat: 34.4260,
    lng: -119.7063,
    mapUrl: null,
    appleMapsUrl: null,
    justCoffee: false,
    coffeeWithFood: true,
    coffeeAsCocktail: false,
    menuItems: [],
  },
  {
    name: "Renaud's Patisserie (Coast Village)",
    address: "1187 Coast Village Rd, Montecito, CA",
    website: "https://www.renaudspatisserie.com",
    phone: "805-565-8760",
    instagram: "renaudspatisserie",
    area: "Montecito",
    lat: 34.4264,
    lng: -119.6327,
    mapUrl: null,
    appleMapsUrl: null,
    justCoffee: false,
    coffeeWithFood: true,
    coffeeAsCocktail: false,
    menuItems: [],
  },
  {
    name: "Renaud's Patisserie (Gelson's)",
    address: "3305 State St, Santa Barbara, CA",
    website: "https://www.renaudspatisserie.com",
    phone: "805-569-2400",
    instagram: "renaudspatisserie",
    area: "Upper State",
    lat: 34.4391,
    lng: -119.7355,
    mapUrl: null,
    appleMapsUrl: null,
    justCoffee: false,
    coffeeWithFood: true,
    coffeeAsCocktail: false,
    menuItems: [],
  },

  // --- Downtown (reused from burger week) ---
  {
    name: "Third Window Brewing (Santa Barbara)",
    address: "406 E Haley St Ste 3, Santa Barbara, CA",
    website: "https://www.thirdwindowbrewing.com",
    phone: "805-979-5090",
    instagram: "thirdwindowbrewing",
    area: "Downtown",
    lat: 34.420992,
    lng: -119.690444,
    mapUrl: "https://maps.app.goo.gl/CxyGVg16v1dAXkVq6",
    appleMapsUrl: "https://maps.apple/p/o2.x6VY5-8B~c4",
    justCoffee: false,
    coffeeWithFood: true,
    coffeeAsCocktail: false,
    menuItems: [],
  },

  // --- Carpinteria (reused from burger week) ---
  {
    name: "Third Window Brewing (Carpinteria)",
    address: "720 Linden Ave, Carpinteria, CA",
    website: "https://www.thirdwindowbrewing.com",
    phone: "+1 (805) 562-6475",
    instagram: "thirdwindowbrewing",
    area: "Carpinteria",
    lat: 34.39704,
    lng: -119.520395,
    mapUrl: "https://maps.app.goo.gl/gpcE5McRYoq2aY4MA",
    appleMapsUrl: "https://maps.apple/p/HhNum2x75sTZXQ",
    justCoffee: false,
    coffeeWithFood: true,
    coffeeAsCocktail: false,
    menuItems: [],
  },

  // ==========================================
  // COFFEE AS COCKTAIL (coffeeAsCocktail: true)
  // ==========================================

  // --- Goleta (reused from burger week) ---
  {
    name: "CAYA Restaurant",
    address: "5650 Calle Real, Goleta, CA",
    website: "https://www.cayarestaurant.com",
    phone: "805-964-1288",
    instagram: "cayarestaurant",
    area: "Goleta",
    lat: 34.441588,
    lng: -119.820858,
    mapUrl: "https://maps.app.goo.gl/KDWoCpGP4Bj5tKxG8",
    appleMapsUrl: "https://maps.apple/p/qsKhePr8N5NbRr",
    justCoffee: false,
    coffeeWithFood: false,
    coffeeAsCocktail: true,
    menuItems: [],
  },

  // --- Goleta ---
  {
    name: "Marisella",
    address: "8301 Hollister Ave, Goleta, CA",
    website: null,
    phone: null,
    instagram: "marisellasb",
    area: "Goleta",
    lat: 34.4247,
    lng: -119.9050,
    mapUrl: null,
    appleMapsUrl: null,
    justCoffee: false,
    coffeeWithFood: false,
    coffeeAsCocktail: true,
    menuItems: [],
  },

  // --- Downtown ---
  {
    name: "Paloma",
    address: "702 Anacapa St, Santa Barbara, CA",
    website: "https://www.palomabar.com",
    phone: "805-966-9090",
    instagram: "paloma_sb",
    area: "Downtown",
    lat: 34.4197,
    lng: -119.6968,
    mapUrl: null,
    appleMapsUrl: null,
    justCoffee: false,
    coffeeWithFood: false,
    coffeeAsCocktail: true,
    menuItems: [],
  },

  // --- Downtown ---
  {
    name: "Sama Sama Kitchen",
    address: "1208 State St, Santa Barbara, CA",
    website: "https://www.samasamakitchen.com",
    phone: "805-845-4472",
    instagram: "samasamakitchen",
    area: "Downtown",
    lat: 34.4252,
    lng: -119.7056,
    mapUrl: null,
    appleMapsUrl: null,
    justCoffee: false,
    coffeeWithFood: false,
    coffeeAsCocktail: true,
    menuItems: [],
  },
];
